### PR TITLE
use static in select fields to make it easier to extend

### PR DESCRIPTION
**Pull request by crissi**
## Summary
use static in select fields to make it easier to extend

## Type of change
- [x ] Misc. change (internal, infrastructure, maintenance, etc.)

### Checklist
- [x ] Existing tests have been adapted and/or new tests have been added
- [x ] Add a CHANGELOG.md entry
- [x ] Update the README.md
- [x ] Code style has been fixed via `composer fix-style`

### CODE REVIEW

**Comment by crissi** [comment]
Ahh fuck, should probably write a test

Hent Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Markus Podar <notifications@github.com>
Sendt: Monday, May 25, 2020 12:08:14 PM
Til: rebing/graphql-laravel <graphql-laravel@noreply.github.com>
Cc: Christian <c2n@live.dk>; Author <author@noreply.github.com>
Emne: Re: [rebing/graphql-laravel] use static in select fields to make it easier to extend (#634)


@mfn commented on this pull request.

How can you extend the class? 🤔

AFAIK it's only instantiated via \Rebing\GraphQL\Support\Field::instanciateSelectFields which is private, so you can't even override the new SelectFields with your own version?

**Comment by mfn** [comment]
Can't merge right now because
image

But the build did run and is green: https://travis-ci.org/github/rebing/graphql-laravel/builds/690896656

🤦

**Comment by mfn** [comment]
Created https://github.com/rebing/graphql-laravel/issues/635 for anyone interested.

**Comment by mfn** [comment]
I definitely used to be able to trigger re-running of travis jobs, but can't anymore. @rebing can you take a look and restart https://travis-ci.org/github/rebing/graphql-laravel/builds/690896656 ?

**Comment by rebing** [comment]
@mfn I've restarted it

**Comment by mfn** [comment]
Purrfect 👍

**Pull request merged**
