### PR TITLE
Correct Lumen routing using regular expression constraints

### LINKED ISSUE #718: Lumen schema name routing does not pass value to GraphQL controller
### Versions:
- graphql-laravel Version: 2.1
- Lumen Version: 6.0
- PHP Version: 7.4

### Description:

The [`GraphQL::routeNameTransformer`](https://github.com/rebing/graphql-laravel/blob/master/src/GraphQL.php#L475) function assigns the [incorrect name]((https://github.com/rebing/graphql-laravel/blob/master/src/GraphQL.php#L495)) to [regular expression routing constraint](https://lumen.laravel.com/docs/6.x/routing#route-parameters) for Lumen. 

### Steps To Reproduce:
1. Modify the [`GraphQLController::query]`(https://github.com/rebing/graphql-laravel/blob/master/src/GraphQLController.php#L26) method to `var_dump($schema)`;
2. Navigate to `<host>/path/to/graphql/root/<schema_name>` and observe a var_dump of null.

### PR DESCRIPTION
**Pull request by sglitowitzsoci**
## Summary
Use correct syntax for Lumen routing with [regular expression constraints](https://lumen.laravel.com/docs/6.x/routing#route-parameters).

Fixes #718 

---

Type of change:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Misc. change (internal, infrastructure, maintenance, etc.)

Checklist:
- [ ] Existing tests have been adapted and/or new tests have been added
- [x] Add a CHANGELOG.md entry
- [ ] Update the README.md
- [ ] Code style has been fixed via `composer fix-style`

### CODE REVIEW

**Comment by mfn** [comment]
I don't use Lumen and it's not possible write unit tests for it, as there's no support.

Would it be possible to come up with a test for https://github.com/rebing/graphql-laravel/blob/master/tests/integration-lumen.sh for this?

**Comment by sglitowitzsoci** [comment]
@mfn Added [here](https://github.com/rebing/graphql-laravel/pull/719/files#diff-a1c7f568af1deca8d7e8f21f90100c4df473760b57c2aa7a8f2702f138e4c2f8R30).

**Review by mfn — APPROVED** [review]
This looks great and the test helped me a lot to verify this, thank you!

---
Before merging I want to look into the (very likely unrelated) failures first.

If you find time, can you add a changelog entry too? If not, I can add it also later.

**Comment by mfn** [comment]
> If not, I can add it also later.

Done!

**Comment by mfn** [comment]
@sglitowitzsoci release is tagged! => https://github.com/rebing/graphql-laravel/releases/tag/6.2.0

**Pull request merged**
