### PR TITLE
Added a function to add custom wrap for the queries or mutations

### PR DESCRIPTION
**Pull request by albertcito**
Now you can create my own wrapper like pagination to inject more options to te resolve function in my GraphQL queries or mutations.
- Added Facade method
- Added unit tests

### CODE REVIEW

**Comment by mfn** [comment]
Awesome, thank you very much for the contribution and thanks for the patience 😄 

(I commit just a smallish fix so the test aligns better with the existing ones)

**Comment by mfn** [comment]
We forgot to add a changelog 😜 fixed with https://github.com/rebing/graphql-laravel/pull/498

**Comment by mfn** [comment]
@albertcito it's now part of the 3.0.0 release! => https://github.com/rebing/graphql-laravel/releases/tag/3.0.0

**Comment by albertcito** [comment]
Awesome !!!!! 🎉

**Pull request merged**
