### PR TITLE
Add parameters support to instance custom fields

### PR DESCRIPTION
**Pull request by emiliogrv**
* added custom field for dates
* added support for the use of parameters in the constructor of any custom-field

### CODE REVIEW

**Comment by emiliogrv** [comment]
Hello,
Is there a problem with this?
I also have another PR to solve this: https://github.com/rebing/graphql-laravel/issues/31 as an alias

**Comment by rebing** [comment]
Sorry, but I don't like a separate field for DateTime, because it can vary so much and I don't think it's necessary

**Comment by emiliogrv** [comment]
Hello,
The DateTime was really an example, I can delete it and make another commit, the idea of PR is to give the opportunity to send parameters to the builder of any custom-field if necessary

**Comment by rebing** [comment]
I still don't quite understand what the PR is trying to accomplish here. What is purpose of the `field` attribute?

**Comment by emiliogrv** [comment]
The attribute `field` is for send the class of custom-field and attribute `params` is for send parameters to constructor funtion of that custom-field
This PR is for that, send parameters to constructor of any custom-field  if need. The DateTime custom.field is only as example of that feature

**Comment by rebing** [comment]
Why not just use `'created_at'` => DateField::class`? What is the use of `params`? Has another package done something like this?

**Comment by emiliogrv** [comment]
> Why not just use 'created_at' => DateField::class?
Because can't send values to constructor of class

> What is the use ofparams`? 
Config any options in the class of custom-field for the internal logic, the name of field in the database, for example for dates, many names of dates can be resolve with only one custom-field class

> Has another package done something like this?
No, that's why I propose this solution, I had the same need in another work project, and that's why I share it

**Pull request closed without merging**
