### PR TITLE
Support class based schemas

### PR DESCRIPTION
**Pull request by jasonvarga**
## Summary

This PR adds support for defining a class based schema.

Rather than defining the entire schema directly in the config file, like this:

```php
'schemas' => [
    'default' => [
        'query' => [
            QueryOne::class,
            QueryTwo::class
        ]
    ]
]
```

You'll be able to define it by specifying a class name:

```php
'schemas' => [
  'default' => \App\GraphQL\MySchema::class
]
```

This class should implement the new `ConfigConvertible` contract which will convert to an array you'd have previously used in the config file.

```php
use Rebing\GraphQL\Support\Contracts\ConfigConvertible;

class MySchema implements ConfigConvertible
{
    public function toConfig(): array
    {
        return [
            'query' => [
                QueryOne::class,
                QueryTwo::class
            ]
        ];
    }
}
```

The reason this would be useful for us (Statamic, a Laravel CMS package) is because we intend to be able to have an entire schema that users can put into their config. We don't want them to have to manually define the config.

Also, we intend to allow third parties to inject their own query classes into our schema. The schema class above is a bit simplified. Ours might look more like this:

```php
class Schema implements ConfigConvertible
{
    private static $customQueries = [];

    public function toConfig(): array
    {
        return [
            'query' => array_merge([
                NativeQueryOne::class,
                NativeQueryTwo::class
            ], static::$customQueries);
        ];
    }

    public static function addQuery($class)
    {
        static::$customQueries[] = $class;
    }
}
```

I'm not quite sure how you feel about the naming of things here though. I used `ConfigConvertible` and `toConfig()` because I saw a `TypeConvertible` interface with `toType()`.

The only _technically_ breaking change here is that if you already used a string, you'd previously get a GraphQL error like `cannot query field "some_query"` and now you'd get a `BindingResolutionException`. But your app wouldn't have been working in the first place so I don't think it really matters.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

### Checklist
- [x] Existing tests have been adapted and/or new tests have been added
- [x] Add a CHANGELOG.md entry
- [x] Update the README.md
- [ ] Code style has been fixed via `composer fix-style`

### CODE REVIEW

**Comment by jasonvarga** [comment]
Not sure why the static analysis is failing. I didn't touch routes.php. Looks like it fails on master too.
The code style wants to make whacky migration class names. Also unrelated to anything in this PR.

🤔 🤷

**Comment by mfn** [comment]
Hey @jasonvarga , thanks for the PR!

I'll check it out as soon as I find time, might take a while though. I wouldn't worry yet about the analyzer, I'll check this out later too.

**Comment by jasonvarga** [comment]
Thanks!

**Review by mfn — APPROVED** [review]
Very nice, LGTM!

Also nice job with https://github.com/statamic/cms/pull/2982 😱 

Will merge & release as soon as everything is green

**Comment by mfn** [comment]
@jasonvarga release as https://github.com/rebing/graphql-laravel/releases/tag/6.3.0 !

**Comment by jasonvarga** [comment]
Awesome, thanks!

**Pull request merged**
