### PR TITLE
Fix schema parsing issue when route prefix is empty string

### PR DESCRIPTION
**Pull request by hello-liang-shan**
## Summary

Fix schema parsing issue

---

Type of change:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Misc. change (internal, infrastructure, maintenance, etc.)

Checklist:
- [x] Existing tests have been adapted and/or new tests have been added
- [x] Add a CHANGELOG.md entry
- [ ] Update the README.md
- [ ] Code style has been fixed via `composer fix-style`

### CODE REVIEW

**Comment by hello-liang-shan** [comment]
@mfn I was going to add this to #888 , but that pr was merged.

**Comment by mfn** [comment]
This only affects when using an empty route prefix, existing routes are not affected?

**Comment by mfn** [comment]
Unrelated, can you please add a changelog entry?

**Comment by hello-liang-shan** [comment]
> This only affects when using an empty route prefix, existing non-empty routes are not affected?

yes. previously, only the empty route prefix had problems.

**Review by mfn — APPROVED** [review]
LGTM, thank you!

I'll put out a patch release later today

**Comment by mfn** [comment]
[Released as 8.2.1](https://github.com/rebing/graphql-laravel/releases/tag/8.2.1)!

**Pull request merged**
