### PR TITLE
Basic directives support

### PR DESCRIPTION
**Pull request by illambo**
## Summary
Attempted integration of directives support, see [changes](https://github.com/rebing/graphql-laravel/pull/703/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R2156) in readme for use case.

#### TODO
 - [ ] Directive location:
   * Request definitions:
      + [ ] query -> seems accessible via ResolveInfo  operation->directives
      + [ ] mutation -> seems accessible via ResolveInfo  operation->directives
      + [ ] subscription -> seems accessible via ResolveInfo  operation->directives
      + [x] field
      + [ ] fragment_definition
      + [ ] fragment_spread
      + [ ] inline_fragment
      + [ ] variable_definition
   * Type system definitions:
      + [ ] schema
      + [ ] scalar
      + [ ] object
      + [ ] field_definition
      + [ ] argument_definition
      + [ ] interface
      + [ ] union
      + [ ] enum
      + [ ] enum_value
      + [ ] input_object
      + [ ] input_field_definition 
 - [ ] Discuss if treating GraphQL directives as middleware or (better) pipeline (see [interesting article](https://blog.logrocket.com/treating-graphql-directives-as-middleware/)) maybe in [default field resolver](https://github.com/rebing/graphql-laravel#default-field-resolver)
 - [ ] Understand possible adaptation of [type-modifiers](https://github.com/rebing/graphql-laravel#type-modifiers)
 - [ ] Tests
 - [ ] Unlock friendsofphp/php-cs-fixer composer dependency

#### DEV NOTES
 - https://www.apollographql.com/docs/apollo-server/schema/creating-directives/
 - underlying layer seems "unready" webonyx/graphql-php#748 webonyx/graphql-php#299
 - webonyx example custom directive - https://github.com/webonyx/graphql-php/issues/308#issuecomment-431197515
 - check implementation https://github.com/diasfs/graphql-php-resolvers
 - https://spec.graphql.org/June2018/#sec-Type-System.Directives

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

### Checklist
- [x] Existing tests have been adapted and/or new tests have been added
- [x] Add a CHANGELOG.md entry
- [x] Update the README.md
- [x] Code style has been fixed via `composer fix-style`

### CODE REVIEW

**Comment by illambo** [comment]
I don't understand why the _Code Analysis / Code Style checker (pull_request)_ step fails :confused:

**Comment by 1070rik** [comment]
Awesome feature! Would love to see this implemented :D

**Comment by mfn** [comment]
> I don't understand why the _Code Analysis / Code Style checker (pull_request)_ step fails 😕

Seems we're hit by https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5342 ; let's worry about this one for now!

**Comment by illambo** [comment]
Yes, seems related to the version of package _friendsofphp/php-cs-fixer_,
in [other pr](https://github.com/rebing/graphql-laravel/pull/701/checks?check_run_id=1510096385) works with _v2.16.8_  but in this fails v2.17.1 (like u link above).
I try to lock temporarily the package version.

**Comment by illambo** [comment]
I close the pr as at the moment I don't have time to continue the implementation I hope to have more time in the future.

**Pull request closed without merging**
