### PR TITLE
Queries and mutations custom visibility in schema introspection

### PR DESCRIPTION
**Pull request by alanwillms**
See #96

### CODE REVIEW

**Comment by alanwillms** [comment]
This is not ready to be merged, I opened this PR to start a discussion

**Comment by alanwillms** [comment]
I think a single method would be better too, but my concern is that `authorize` can be scoped according to the `$args` param. For example, one may feel encouraged to use `authorize` to check if the user calling `updatePost` is the owner of the post (`$post->user_id == Auth::id()`).

Well, anyway if someone does that, he or she will get an error while introspecting can fix it by put the fine-grained level authorization in the proper place (inside `resolve` maybe).

I will change to use `authorize` instead.

**Comment by alanwillms** [comment]
>  and maybe have another boolean field in the config, which toggles visibility based on authorizations

Do you think that configuration should be per query/mutation or per schema?

**Comment by rebing** [comment]
I think the configuration should apply to the whole schema

**Comment by alanwillms** [comment]
@rebing please take a look now

**Comment by rebing** [comment]
I'm sorry, but I'm not sure that's still the right course, since an empty array is passed to `authorize` instead of query arguments. Also, all authorize functions are executed, which is very costly and unnecessary in most cases.

Perhaps it should be based on middleware instead?

**Comment by alanwillms** [comment]
No problem, but that's beyond my knowledge about Laravel. Can you point me to the right direction?

**Comment by rebing** [comment]
I'm not exactly sure how to do it either. It's actually probably not even possible to evaluate the middleware before schema introspection.

**Comment by alanwillms** [comment]
If anybody find this, there is this solution for the problem:

https://github.com/fidelize/graphql-laravel-authorize-introspection

It is not the most beautiful or clean solution, but it works.

**Pull request closed without merging**
