### PR TITLE
Fix interface fields selection

### LINKED ISSUE #605: Problem with interface SelectFields and inline fragments
### Versions:
- graphql-laravel Version: 5.0.0-rc2
- Laravel Version: 6.18.1 
- PHP Version: 7.2.22

### Description:

I'm having problems with interface SelectFields and inline fragments.
The query seems does not extract the requested data from interface (see below query with inline fragments), maybe is related to SelectFields.

### Steps To Reproduce:

- Setup example

```
// migrations

Schema::create('humans', function (Blueprint $table) {
      $table->bigIncrements('id');
      $table->string('skin');
      $table->timestamps();
});

Schema::create('droids', function (Blueprint $table) {
      $table->bigIncrements('id');
      $table->string('metal');
      $table->timestamps();
});

// interface

class CharacterInterfaceType extends InterfaceType
{
    protected $attributes = [
        'name' => 'CharacterInterface',
        'description' => 'An example interface',
    ];

    public function fields(): array
    {
        return [
            'id' => [
                'type' => Type::id(),
            ],
        ];
    }

    /**
     * @param $root
     * @return Type
     */
    public function resolveType($root): ?Type
    {
        $type = null;

        if (! is_null($root)) {
            switch (get_class($root)) {
                case \App\Human::class: $type = GraphQL::type('Human'); break;
                case \App\Droid::class: $type = GraphQL::type('Droid'); break;
            }
        }

        return $type;
    }
}

// types

class DroidType extends GraphQLType
{
    protected $attributes = [
        'name' => 'Droid',
        'description' => 'A type',
        'model' => Droid::class,
    ];

    public function fields(): array
    {
        $characterInterface = GraphQL::type('CharacterInterface');
        return array_merge($characterInterface->getFields(), [
            'metal' => [
                'type'          => Type::string(),
                'description'   => 'The metal',
            ],

        ]);
    }

    public function interfaces(): array
    {
        return [
            GraphQL::type('CharacterInterface')
        ];
    }
}

class HumanType extends GraphQLType
{
    protected $attributes = [
        'name' => 'Human',
        'description' => 'A type',
        'model' => Human::class,
    ];

    public function fields(): array
    {
        $characterInterface = GraphQL::type('CharacterInterface');
        return array_merge($characterInterface->getFields(), [
            'skin' => [
                'type'          => Type::string(),
                'description'   => 'The skin',
            ],

        ]);
    }

    public function interfaces(): array
    {
        return [
            GraphQL::type('CharacterInterface')
        ];
    }
}

// query

class CharactersQuery extends Query
{
    protected $attributes = [
        'name' => 'characters',
        'description' => 'A query'
    ];

    public function type(): Type
    {
        return Type::listOf(GraphQL::type('CharacterInterface'));
    }

    public function args(): array
    {
        return [];
    }

    public function resolve($root, $args, $context, ResolveInfo $resolveInfo, Closure $getSelectFields)
    {
        /** @var SelectFields $fields */
        $fields = $getSelectFields();
        $select = $fields->getSelect();
        $relations = $fields->getRelations();

        // this example force to human extractions
        return \App\Human::select($select)->with($relations)->get(); // this  not work ... 
        //return \App\Human::with($relations)->get(); // this  not work ...
        //return \App\Human::get(); // !! this work ...
    }
}
```
- Seed some human ..
- Run query
```
query Characters {
  characters {
    __typename
    id
    ...on Droid {
      id
      metal
    }
    ...on Human {
      id
      skin
    }
  }
}
```
- Check extracted data, human skin is null

### PR DESCRIPTION
**Pull request by illambo**
## Summary
Fix interface fields selection.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist
- [x] Existing tests have been adapted and/or new tests have been added

## Links
Resolve #605 
Resolve https://github.com/rebing/graphql-laravel/issues/491

### CODE REVIEW

**Comment by illambo** [comment]
Need help in order to complete checklist (Existing tests have been adapted and/or new tests have been added).

**Comment by mfn** [comment]
@crissi what do you think about this? Looks "sane" to me, but 🤷‍♀️

**Comment by crissi** [comment]
Does the sql alias still work?

The test does not seem to cover the bug, I only see changes to the sql

**Comment by illambo** [comment]
I try to elaborate a targeted test if needs.

**Comment by crissi** [comment]
Of cause it would be better if the missing foreign key was added instead of *, but that might be difficult

**Comment by illambo** [comment]
I agree @crissi but I don't have time now to go further, is an acceptable solution for you now?
Thanks

**Comment by mfn** [comment]
Would this also fix https://github.com/rebing/graphql-laravel/issues/491 ?

Would be a brief summary of _how_ we fixed it? Would the following be an accurate description? 
> Fix interface field selection by forgoing individual column selects and simply allows fetch the complete model.

?

thanks

**Comment by illambo** [comment]
Yes, I think also fix that, but the unit test actually don’t cover this case (maybe later I can try to add that if needs).
The description seems good for me.

**Comment by illambo** [comment]
@mfn ok, done

**Comment by mfn** [comment]
https://github.com/rebing/graphql-laravel/releases/tag/5.0.0 has been released which includes this!

**Pull request merged**
