### PR TITLE
Auto-resolve unresolved aliased fields

### PR DESCRIPTION
**Pull request by ZaidBarghouthi**
Adds simple default resolver to aliased fields when no resolver is present. 

**I'm not sure how to test this properly ( please comment )**

#280

### CODE REVIEW

**Comment by ZaidBarghouthi** [comment]
please consider adding a `editorconfig` file.

**Comment by mfn** [comment]
> please consider adding a `editorconfig` file.

👍 added in https://github.com/rebing/graphql-laravel/commit/b7ec923370e0bf3fd85ed1d83074f105ef50a828 !

**Comment by ZaidBarghouthi** [comment]
Should we have a check that this new resolver only applies when there is a model defined?

**Comment by mfn** [comment]
Label as blocked until https://github.com/rebing/graphql-laravel/pull/289 can land, after which we can cover the change with a test

**Comment by mfn** [comment]
In https://github.com/rebing/graphql-laravel/pull/289 I've now added the test`\Rebing\GraphQL\Tests\Database\SelectFieldsTest::testWithSelectFieldsAndModelAndAlias` which I expect will "break" and needs to be adjusted after this PR.

**Comment by ZaidBarghouthi** [comment]
Yup.

**Comment by mfn** [comment]
Thanks for the PR!

I've merged this into master and also the [recent v1 branch](https://github.com/rebing/graphql-laravel/issues/286) and cut a [new v1.22.0 release](https://github.com/rebing/graphql-laravel/releases/tag/v1.22.0) (hopefully it works 🤞 as expected).

> Should we have a check that this new resolver only applies when there is a model defined?

There does not seem to be a technical reason for this _yet_.

For simple attribute aliases it seems the model is not required. Without it, the generated SQL query will simple not use qualified names. I.e. the difference will be:

- with model
  ```sql
  select "posts"."id", "posts"."title" from "posts" where "posts"."id" = ? limit 1;
  ```
- without model
  ```sql
  select "id", "title" from "posts" where "posts"."id" = ? limit 1;
  ```
But nevertheless it will work correctly; as the SelectFields in general does.

**Comment by ZaidBarghouthi** [comment]
Thank you @mfn

**Pull request merged**
