### PR TITLE
WiP [SELECTFIELDS][ALWAYSFIELDS] Always select morph relation

### PR DESCRIPTION
**Pull request by ZaidBarghouthi**
#369

### CODE REVIEW

**Comment by ZaidBarghouthi** [comment]
@mfn Thanks for taking the time. Any ideas?

**Comment by mfn** [comment]
> Any ideas?

You mean about.. what exactly? :)

Btw, thanks for the test, this is really cool to have (even if the feature isn't there).

[I had to do some minor code adjustments](https://github.com/rebing/graphql-laravel/pull/370/commits/537828a4b12744596e6981f76fe54920022a2468), not sure how that could work on Travis at all 🤔

**Comment by ZaidBarghouthi** [comment]
> > Any ideas?
> 
> You mean about.. what exactly? :)
> 
> Btw, thanks for the test, this is really cool to have (even if the feature isn't there).
> 
> [I had to do some minor code adjustments](https://github.com/rebing/graphql-laravel/pull/370/commits/537828a4b12744596e6981f76fe54920022a2468), not sure how that could work on Travis at all 🤔

You are welcome!

Ideas about how to tackle the issue. I'm not sure what to do here ~_~.

```php
protected static function addAlwaysFields(FieldDefinition $fieldObject, array &$select, ?string $parentTable, bool $forRelation = false): void
{
    if (isset($fieldObject->config['always'])) {
        $always = $fieldObject->config['always'];

        if (is_string($always)) {
            $always = explode(',', $always);
        }

        // Get as 'field' => true
        foreach ($always as $field) {
            self::addFieldToSelect($field, $select, $parentTable, $forRelation);
        }
    }
}
```

**Comment by ZaidBarghouthi** [comment]
> [I had to do some minor code adjustments](https://github.com/rebing/graphql-laravel/pull/370/commits/537828a4b12744596e6981f76fe54920022a2468), not sure how that could work on Travis at all 🤔

Yea... I stated putting the files in tests/Support/Types,, then I figured out the new tests. Good stuff.

**Comment by mfn** [comment]
> Ideas about how to tackle the issue.

Sorry, not at the moment :|

I'm preparing the 2.0 release and still have to tackle some things there. Also I have not much experience with morph relations, never used them so far.

**Comment by ZaidBarghouthi** [comment]
> I'm preparing the 2.0 release and still have to tackle some things there. Also I have not much experience with morph relations, never used them so far.

Thanks ok. About the new release, consider adding a road map project.

**Pull request merged**
