### PR TITLE
refactor routes file

### PR DESCRIPTION
**Pull request by crissi**
## Summary
Refactor of routes file

The logic for specific controller config for mutation and query was 95% a like. So therefore the refactor. This will also make it easier to add subscription specific routing in the future

## Type of change
- [x] Misc. change (internal, infrastructure, maintenance, etc.)

### CODE REVIEW

**Comment by mfn** [comment]
I tried once more to understand the changes of the refactoring but had to give up, no idea.

Besides the tests in here I verified it doesn't break some applications I use the library in 👍 

Would you mean adding some more explanation in the commit message what / why the refactoring?

thanks!

**Comment by crissi** [comment]
updated

**Comment by mfn** [comment]
super cool.

can you squash all commits into _and_ include that actual information in the commit message itself, please?

I'll merge it then, thanks!

**Comment by crissi** [comment]
ready, if you didn't notice:)

**Comment by mfn** [comment]
Didn't 🤷‍♀️ :-)

Thanks!

**Comment by mfn** [comment]
https://github.com/rebing/graphql-laravel/releases/tag/5.0.0 has been released which includes this!

**Pull request merged**
