### PR TITLE
update routes.php

### PR DESCRIPTION
**Pull request by MonsterDong**
multi level path for route where

### CODE REVIEW

**Comment by mfn** [comment]
Please explain in more detail what this is about and also add some tests

**Comment by MonsterDong** [comment]
> Please explain in more detail what this is about and also add some tests

image
image

I defined two schemas, user/me and merchant/me. Merchant /me configured the middleware mustBindPhone(which must be tied with the phone to access it), but when I visited user/me schemas, I chose the middleware of merchant/me schemas

**Comment by MonsterDong** [comment]
Versions:
graphql-laravel Version: v1.24
Laravel Version: 5.8
PHP Version: 7.2

**Comment by mfn** [comment]
Is the problem that the `/` in the schema name confuses the routing?

**Comment by MonsterDong** [comment]
> Is the problem that the `/` in the schema name confuses the routing?
Yes, this problem causes $router->where() not to take effect

**Comment by mfn** [comment]
It seems you added it to the "if not lumen" condition; any idea how both can be supported?

**Comment by MonsterDong** [comment]
> It seems you added it to the "if not lumen" condition; any idea how both can be supported?
In the lumen
image


In the code

image

So there's no problem with lumen

**Comment by mfn** [comment]
ping @MonsterDong

**Comment by mfn** [comment]
Closing due to missing feedback (i.e. tests, in this case; sorry but can't accept such changes without them!)

**Pull request closed without merging**
