### PR TITLE
redo validation for fields

### PR DESCRIPTION
**Pull request by crissi**
## Summary
Fixes https://github.com/rebing/graphql-laravel/issues/602

Rules never worked in field arguments. (redone)

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

### Checklist
- [x] Existing tests have been adapted and/or new tests have been added
- [x] Add a CHANGELOG.md entry
- [x] Code style has been fixed via `composer fix-style`

### CODE REVIEW

**Comment by crissi** [comment]
redid the pr + added the __typename to one of the tests.

**Comment by mfn** [comment]
Jap, saw it! Sorry, short on time currently. Not forgotten, it's in the queue!

**Comment by crissi** [comment]
Awesome, keep up the good work :muscle:

**Comment by mfn** [comment]
Sorry for the late feedback; I hope I'll find more time this week.

At a first glance however, I hesitated to go through the whole PR again because the commit messages and changes would kind of require that.

My sincere suggestion would be to make this PR a bit simpler to review:
- one commit which reverts the revert I did (i.e. revert fb9dace2f231b32bf7af1d3b53923ade4a56f339 )
- one other commit with all the fixes (__typename, changelog, etc.)

The goal would be: since I already reviewed the original PR, I've less overhead and can concentrate more on the "delta" and knowing that the other commit is an (untouched) revert.

This also has other benefits like providing a very clear git history _on its own_ without depending on the conversation here on github (not that this is mandatory, but it really makes the whole thing within just the git repo itself transparent).

I again apologize for the delay and that I ask of this now that the PR is laying around for over a month, but what you consider this? (totally fine for me to force-push this over this PR).

**Comment by crissi** [comment]
separated the __typename fix

**Pull request merged**
