### PR TITLE
Make Larastan fly

### PR DESCRIPTION
**Pull request by szepeviktor**
From https://github.com/nunomaduro/larastan/issues/273

### CODE REVIEW

**Comment by mfn** [comment]
I locally applied your hacker `sed` change ;) and commented out the line referencing the Lumen class:
```
$ vendor/bin/phpstan analyse src
Note: Using configuration file /Users/user/src/graphql-laravel/phpstan.neon.dist.
 26/26 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

                                                                                                                        
 [OK] No errors                                                                    
```

**Comment by szepeviktor** [comment]
@mfn Automated!

**Comment by szepeviktor** [comment]
This is not a PR but a test - see the removed tests!

**Comment by szepeviktor** [comment]
@mfn Please consider raising test Level to 2, that is the minimum sustaining the project.

You may have to write a tiny PHPStan extension (service) or introduce new `ignoreErrors`

**Pull request closed without merging**
