### PR TITLE
Rewrite and simplify how schemas are handled

### PR DESCRIPTION
**Pull request by mfn**
## Summary
Ref: https://github.com/rebing/graphql-laravel/issues/778

Schemas don't need to be booted anymore upfront and any action trying
to acquire a schema for execution now requires the "schema name", which
is used to build it from the configuration.
These schemas are then stored in `\Rebing\GraphQL\GraphQL::$schemas`
for as long as the process runs.

These simplifications removed the ability to declare ad-hoc schemas
via passing around schemas or schema config arrays to e.g.
`\Rebing\GraphQL\GraphQL::query` via the `$opts` parameter.
`$opts['schema']` now in fact means "schema name".

Schemas not based on the configuration can still be added manually via
`buildSchemaFromConfig()` and `addSchema()`, in which case `schema()`
will _not go through the configuration (as it first looks up `::$schemas`).

- `\Rebing\GraphQL\GraphQLServiceProvider::bootSchemas` is gone
- It's not possible anymore to "merge" schemas (i.e. merging schema
  config arrays)
- `\Rebing\GraphQL\GraphQL::getSchemaConfiguration()` is gone due to
  the simplifications.

---

Type of change:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Misc. change (internal, infrastructure, maintenance, etc.)

Checklist:
- [ ] Existing tests have been adapted and/or new tests have been added
- [ ] Add a CHANGELOG.md entry
- [ ] Update the README.md
- [ ] Code style has been fixed via `composer fix-style`

### CODE REVIEW

**Comment by mfn** [comment]
Pinging recent contributors @illambo and @crissi for feedback, if you've time!

I also plan to also simplify the type handling (see https://github.com/rebing/graphql-laravel/issues/778 ) but went for the schemas as a first step.

**Comment by crissi** [comment]
Don't understand most of the schema logic. But I can try testing in on production code if that can help.

**Comment by mfn** [comment]
> Don't understand most of the schema logic

That's how I felt about the existing code and hoped to improve (aka simplify) the current version.

> But I can try testing in on production code if that can help.

That would definitely be appreciated! There's no rush here, thanks!

**Comment by illambo** [comment]
Hi, I took a quick look and I think the simplification is good, in general I think that simplification and cleaning is what it takes to "freshen up" the package. 
I have never gone into it and I have never had the particular need for it so I am not sure what implications it may have. 
I would take it forward anyway.

**Comment by mfn** [comment]
@crissi did you have chance to check it out?

**Comment by crissi** [comment]
I sweat it out. On my todo list on tuesday when I am back at the office!

Christian Nielsen
________________________________
Fra: Markus Podar ***@***.***>
Sendt: 21. maj 2021 17:49
Til: rebing/graphql-laravel ***@***.***>
Cc: Christian ***@***.***>; Mention ***@***.***>
Emne: Re: [rebing/graphql-laravel] Rewrite and simplify how schemas are handled (#779)


@crissi<https://github.com/crissi> did you have chance to check it out?

**Comment by crissi** [comment]
Tested on a production build and everything seems to work 👍

**Comment by mfn** [comment]
@crissi thank you so much! This matches my experience, too.

I'll tag a new RC with this one

**Pull request merged**
