### PR TITLE
Attributes starts as an array so define it as such

### PR DESCRIPTION
**Pull request by tm1000**
## Summary
This prevents warnings from Psalm (Static Analysis)

---

Type of change:
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [X] Misc. change (internal, infrastructure, maintenance, etc.)

Checklist:
- [ ] Existing tests have been adapted and/or new tests have been added
- [ ] Add a CHANGELOG.md entry
- [ ] Update the README.md
- [x] Code style has been fixed via `composer fix-style`

### CODE REVIEW

**Review by mfn — APPROVED** [review]
👍🏼

**Comment by tm1000** [comment]
@mfn want me to do one for master too?

**Comment by mfn** [comment]
> @mfn want me to do one for master too?

Not necessary, already on it!

**Comment by tm1000** [comment]
Awesome thanks!!

**Comment by mfn** [comment]
phpstan doesn't like just `@var array` (in the level of reporting we use) and thus needs a more specific type hint; I've changed to to `array<string,mixed>` now in `master`, see https://github.com/rebing/graphql-laravel/commit/0a3d6eca106aaaa9742c568f70e837be0efaa0fc#diff-8de28f31c3270bde507008d320eb9222158a1db79ea4ca2e7842e0fa15bfde5aR23

Unfortunately the tests in the 7.x branch will fail now, but I don't expect any other changes there. Indeed, I was surprised finding a PR targeting this branch :)

Once I release version 8 ("soon"), I will delete that branch.

**Comment by tm1000** [comment]
Psalm should be able to read that as well. 

As for 8 I check in and see every so often where you are at with it. Looking forward to its release

**Comment by mfn** [comment]
> Once I release version 8 ("soon"), I will delete that branch.

FTR, 8.0.0 was released https://github.com/rebing/graphql-laravel/discussions/857 and thus I deleted the 7.x branch!

**Pull request merged**
